image: docker:18.09.9
services:
  - docker:18.09.9-dind
  
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin

build-ubuntu-1404:
  stage: build
  script:
    - docker build --pull -t alvisisme/ubuntu:14.04 -f 14.04/Dockerfile 14.04
    - docker push alvisisme/ubuntu:14.04
  only:
    - master

build-ubuntu-1604:
  stage: build
  script:
    - docker build --pull -t alvisisme/ubuntu:16.04 -f 16.04/Dockerfile 16.04
    - docker push alvisisme/ubuntu:16.04
  only:
    - master

build-ubuntu-1804:
  stage: build
  script:
    - docker build --pull -t alvisisme/ubuntu:18.04 -f 18.04/Dockerfile 18.04
    - docker push alvisisme/ubuntu:18.04
  only:
    - master
