language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

env:
  - UBUNTU_VERSION=14.04
  - UBUNTU_VERSION=16.04
  - UBUNTU_VERSION=18.04

script:
  - echo "$ALIYUN_PASSWORD" | docker login -u "$ALIYUN_USERNAME" --password-stdin registry.cn-hangzhou.aliyuncs.com
  - docker tag alvisisme/ubuntu:$UBUNTU_VERSION registry.cn-hangzhou.aliyuncs.com/alvisisme/ubuntu:$UBUNTU_VERSION
  - docker push registry.cn-hangzhou.aliyuncs.com/alvisisme/ubuntu:$UBUNTU_VERSION
